Update publish-dashboard.yml

diff --git a/.github/workflows/publish-dashboard.yml b/.github/workflows/publish-dashboard.yml
--- a/.github/workflows/publish-dashboard.yml
+++ b/.github/workflows/publish-dashboard.yml
@@ -15,6 +15,13 @@ jobs:
       - name: Check out the code
         uses: actions/checkout@v4
 
+      - name: Verify Docker Hub credentials
+        run: |
+          if [[ -z "${{ secrets.DOCKER_USERNAME }}" || -z "${{ secrets.DOCKER_PASSWORD }}" ]]; then
+            echo "Error: Missing Docker Hub credentials";
+            exit 1;
+          fi
+
       - name: Log in to Docker Hub
         run: |
           echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
